include: package:effective_dart/analysis_options.1.2.0.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_classes_with_only_static_members: false
    file_names: false
    use_setters_to_change_properties: false
